### ISSUE TITLE
When Ticket Admin edits a request through _admin/requests.php tickets can be dropped from the request

### ISSUE THREAD

**Issue by pboyd04** [BurningFlipside/Tickets#26]
This happened to 17 requests in 2016.

**Comment by pboyd04** [comment]
@russelltsherman 
To fix this and #7 I'm thinking about just getting rid of the tblRequestedTickets and tblRequestDonation and simply having a JSON field in the tblTicketRequest that includes all the tickets and another than includes all the donations as an array. We don't really use the SQL server to search in those child tables. So I don't think this has much of a downside. What do you think?

**Comment by russelltsherman** [comment]
it sounds ok.. 

how do we query for donation totals.. through the view tables?

**Comment by pboyd04** [comment]
The JSON query operators in MySQL are still pretty rudimentary so we'd probably end up doing that in code. For the simple case (i.e. we only have one donation type) I could add an additional numeric field that is the total donation for the request. Then the query would be pretty simple.

**Comment by pboyd04** [comment]
Fixed
