### ISSUE TITLE
when no donation types are configured do not show the Donations header in request form

### ISSUE THREAD

**Issue by bhedana** [BurningFlipside/Tickets#3]
<img width="295" alt="screenshot 2017-01-05 09 46 57" src="https://cloud.githubusercontent.com/assets/13397/21686764/1708673c-d32c-11e6-97fb-c13a40acaff6.png">

**Comment by pboyd04** [comment]
Fixed on server. Will push to git soon.

**Comment by pboyd04** [comment]
Fixed by changes to js/request.js in https://github.com/BurningFlipside/Tickets/pull/6/commits/07739f49ca62269ef6803c8a1f311b743c5869ee
