### ISSUE TITLE
API should apply default filter

### ISSUE THREAD

**Issue by ghost** [BurningFlipside/Tickets#8]
Lets change the API to set a default filter if none is provided..

Currently we are required to update javascripts each event year to provide the API with the current filter year (see js/index.js)

<img width="702" alt="screenshot 2017-01-07 15 03 48" src="https://cloud.githubusercontent.com/assets/13397/21745164/99c48614-d4ea-11e6-83a5-70bc90a40ce0.png">

**Comment by pboyd04** [comment]
My plan is to actually add a special value called current that the API would handle. I just haven't gotten around to it yet.
